services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: server local
    env_file:
      - .env_encoded
    ports:
      - "8080:8080"
    volumes:
      - ./build/libs/:/app/plugins/
